name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there 👋! Thanks for contributing. Keep on! :)'' first issue'
        pr-message: 'Congrats to your first pull request 🎉! Please notify the main contributors of the repository to review and approve your PR.'' first pr'
